spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: true
    encoding: utf-8
    enabled: true
    prefix: classpath:/static/
    suffix: .html
    datasource:
      url: jdbc:mysql://localhost:3306/soul?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&&serverTimezone=UTC
      username: root
      password: 12abAB
      dbcp2:
        driver-class-name: com.mysql.jdbc.Driver

management:
  health:
    defaults:
      enabled: false

soul:
  # Soul 针对 SpringMVC 的配置项，对应 SoulHttpConfig 配置类
  http:
    admin-url: http://127.0.0.1:9095 # Soul Admin 地址
    context-path: /sb-demo-api # 设置在 Soul 网关的路由前缀，例如说 /order、/product 等等。
    # 后续，网关会根据该 context-path 来进行路由
    app-name: sb-demo-service # 应用名。未配置情况下，默认使用 `spring.application.name` 配置项
    port: 8080 #你本项目的启动端口
    full: false   # 设置true 代表代理你的整个服务，false表示代理你其中某几个controller